canvas = document.getElementById("mycanvas");
ctx = canvas.getContext("2d");
width = 10;
ctx.beginPath();
ctx.strokeStyle = "blue";
ctx.lineWidth = width;
ctx.arc(350, 200, 40, 0, 2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "yellow";
ctx.lineWidth = width;
ctx.arc(420, 200, 40, 0, 2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "black";
ctx.lineWidth = width;
ctx.arc(490, 200, 40, 0, 2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "green";
ctx.lineWidth = width;
ctx.arc(395, 250, 40, 0, 2*Math.PI);
ctx.stroke();
ctx.beginPath();
ctx.strokeStyle = "red";
ctx.lineWidth = width;
ctx.arc(445, 250, 40, 0, 2*Math.PI);
ctx.stroke();